//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTraFashion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrafashionEntities : DbContext
    {
        public TrafashionEntities()
            : base("name=TrafashionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_slide_tra> tbl_slide_tra { get; set; }
        public virtual DbSet<tbl_products_tra> tbl_products_tra { get; set; }
        public virtual DbSet<tblSysPicture> tblSysPictures { get; set; }
        public virtual DbSet<tbl_blog_tra> tbl_blog_tra { get; set; }
    }
}
