//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTraFashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_blog_tra
    {
        public int id_blog_tra { get; set; }
        public string titile_blog_tra { get; set; }
        public string short_des_blog_tra { get; set; }
        public string des_blog_tra { get; set; }
        public Nullable<int> status_blog_tra { get; set; }
        public Nullable<int> type_blog_tra { get; set; }
        public Nullable<System.DateTime> create_date_blog_tra { get; set; }
        public string img_blog_tra { get; set; }
        public string video_blog_tra { get; set; }
        public Nullable<int> id_company { get; set; }
    }
}
