//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTraFashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_products_tra
    {
        public int id_products_tra { get; set; }
        public string img_products_tra { get; set; }
        public string img1_products_tra { get; set; }
        public string img2_products_tra { get; set; }
        public string img3_products_tra { get; set; }
        public string name_products_tra { get; set; }
        public string code_products_tra { get; set; }
        public string des_products_tra { get; set; }
        public Nullable<int> status_products_tra { get; set; }
        public string newprice_products_tra { get; set; }
        public string oldprice_products_tra { get; set; }
    }
}
