//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTraFashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_slide_tra
    {
        public int id_slide_tra { get; set; }
        public string img_slide_tra { get; set; }
        public string title_slide_tra { get; set; }
        public string des_slide_tra { get; set; }
        public Nullable<int> status_slide_tra { get; set; }
    }
}
